### ISSUE TITLE
论文

### ISSUE THREAD

**Issue by enhuishu** [zhongniuniu/PAMRFuse-plus#2]
这篇论文是借鉴了cddfuse和umf-cmgr？请问有训练数据提供吗？

**Comment by zhongniuniu** [comment]
感谢您的提问！

是的，这篇论文确实借鉴了 cddfuse 和 umf-cmgr，并将它们结合起来，旨在提高医学图像融合任务中的配准和融合效果。此外，我们还首次从下游任务的角度验证了医学图像融合在高级视觉任务中的表现。

关于训练数据，目前论文还在审稿阶段，因此我们暂时不能公开完整的训练数据。待文章发表后，我们会及时公开相关数据。同时，我们在 GitHub 上提供了部分测试数据，以便大家验证我们的性能。

再次感谢您的关注和提问，期待与您的进一步交流！
